/**
  ******************************************************************************
  * @file app_digital_input.c
  * @author Suu Nguyen Van - FPT Company 0971346938
  * @version V1.0
  * @date 27-04-2026
  ******************************************************************************
  * 
  *
  ******************************************************************************
  */

#include "app_digital_input.h"
#include "main.h"

/* ========================= Private filter types ========================= */

typedef struct
{
    uint8_t  Input;       /* Raw input signal: 0 or 1 */
    uint16_t VTcount1;    /* Counter for stable high level */
    uint16_t VTcount0;    /* Counter for stable low level */
    uint16_t VTmax;       /* Filter threshold, unit = update cycle */
    uint8_t  Inverse;     /* 0: normal output, 1: inverted output */
    uint8_t  Output;      /* Filtered output signal */
} INPUT_FILTER;

typedef struct
{
    uint8_t StatePre;     /* Previous state */
    uint8_t StateNew;     /* Current state */
    uint8_t FlagFalling;  /* Falling edge flag: 1 -> 0 */
    uint8_t FlagRising;   /* Rising edge flag: 0 -> 1 */
} EDGE_TRIGGER;

typedef struct
{
    GPIO_TypeDef *GPIOx;
    uint16_t GPIO_Pin;

    INPUT_FILTER Filter;
    EDGE_TRIGGER Edge;
} APP_DIGITAL_INPUT;

/* ========================= Private defines ========================= */

/*
 * If AppDigitalInput_1msTask() is called every 1ms:
 * VTmax = 50 means debounce time is approximately 50ms.
 */
#define DIGITAL_INPUT_DEFAULT_DEBOUNCE_MS    50u

#define INPUT_FILTER_DEFAULTS          \
{                                      \
    0u,                                \
    0u,                                \
    0u,                                \
    DIGITAL_INPUT_DEFAULT_DEBOUNCE_MS, \
    0u,                                \
    1u                                 \
}

#define EDGE_TRIGGER_DEFAULTS          \
{                                      \
    1u,                                \
    1u,                                \
    0u,                                \
    0u                                 \
}

/* ========================= Private variables ========================= */

/*
 * Map the actual GPIO pins used in this project here.
 * SWITCH1_GPIO_Port, SWITCH1_Pin, etc. must match the names generated by CubeMX in main.h.
 */
static APP_DIGITAL_INPUT DigitalInputs[DIGITAL_INPUT_MAX] =
{
    [DIGITAL_INPUT_SWITCH_1] = {I1_GPIO_Port, I1_Pin, INPUT_FILTER_DEFAULTS, EDGE_TRIGGER_DEFAULTS},
    [DIGITAL_INPUT_SWITCH_2] = {I2_GPIO_Port, I2_Pin, INPUT_FILTER_DEFAULTS, EDGE_TRIGGER_DEFAULTS},
    [DIGITAL_INPUT_SWITCH_3] = {I3_GPIO_Port, I3_Pin, INPUT_FILTER_DEFAULTS, EDGE_TRIGGER_DEFAULTS},
    [DIGITAL_INPUT_SWITCH_4] = {I4_GPIO_Port, I4_Pin, INPUT_FILTER_DEFAULTS, EDGE_TRIGGER_DEFAULTS},
    [DIGITAL_INPUT_SWITCH_5] = {I5_GPIO_Port, I5_Pin, INPUT_FILTER_DEFAULTS, EDGE_TRIGGER_DEFAULTS},
};

/* ========================= Private function prototypes ========================= */

static void DigitalIntegralFilter(INPUT_FILTER *filter);
static void BothEdgeTriggerDetection(EDGE_TRIGGER *edge);
static uint8_t AppDigitalInput_IsValidId(APP_DIGITAL_INPUT_ID id);

/* ========================= Private functions ========================= */

static void DigitalIntegralFilter(INPUT_FILTER *filter)
{
    if (filter == 0)
    {
        return;
    }

    if (filter->Input != 0u)
    {
        if (filter->VTcount1 < filter->VTmax)
        {
            filter->VTcount1++;
            filter->VTcount0 = 0u;
        }
        else
        {
            filter->Output = (uint8_t)(1u ^ filter->Inverse);
        }
    }
    else
    {
        if (filter->VTcount0 < filter->VTmax)
        {
            filter->VTcount0++;
            filter->VTcount1 = 0u;
        }
        else
        {
            filter->Output = (uint8_t)(0u ^ filter->Inverse);
        }
    }
}

static void BothEdgeTriggerDetection(EDGE_TRIGGER *edge)
{
    if (edge == 0)
    {
        return;
    }

    if ((edge->StatePre == 1u) && (edge->StateNew == 0u))
    {
        edge->FlagFalling = 1u;
    }
    else if ((edge->StatePre == 0u) && (edge->StateNew == 1u))
    {
        edge->FlagRising = 1u;
    }

    edge->StatePre = edge->StateNew;
}

static uint8_t AppDigitalInput_IsValidId(APP_DIGITAL_INPUT_ID id)
{
    return (id < DIGITAL_INPUT_MAX);
}

/* ========================= Public functions ========================= */

void AppDigitalInput_Init(void)
{
    uint8_t i;
    uint8_t gpio_state;

    for (i = 0u; i < DIGITAL_INPUT_MAX; i++)
    {
        gpio_state = (uint8_t)HAL_GPIO_ReadPin(DigitalInputs[i].GPIOx,
                                               DigitalInputs[i].GPIO_Pin);

        DigitalInputs[i].Filter.Input = gpio_state;
        DigitalInputs[i].Filter.Output = gpio_state;
        DigitalInputs[i].Filter.VTcount1 = 0u;
        DigitalInputs[i].Filter.VTcount0 = 0u;

        DigitalInputs[i].Edge.StatePre = gpio_state;
        DigitalInputs[i].Edge.StateNew = gpio_state;
        DigitalInputs[i].Edge.FlagFalling = 0u;
        DigitalInputs[i].Edge.FlagRising = 0u;
    }
}

void AppDigitalInput_1msTask(void)
{
    uint8_t i;

    for (i = 0u; i < DIGITAL_INPUT_MAX; i++)
    {
        DigitalInputs[i].Filter.Input =
            (uint8_t)HAL_GPIO_ReadPin(DigitalInputs[i].GPIOx,
                                      DigitalInputs[i].GPIO_Pin);

        DigitalIntegralFilter(&DigitalInputs[i].Filter);

        DigitalInputs[i].Edge.StateNew = DigitalInputs[i].Filter.Output;
        BothEdgeTriggerDetection(&DigitalInputs[i].Edge);
    }
}

/*
 * Used for active-low switch input with pull-up:
 * OFF = 1
 * ON  = 0
 */
uint8_t AppDigitalInput_Check(APP_DIGITAL_INPUT_ID id)
{
    if (!AppDigitalInput_IsValidId(id))
    {
        return 0u;
    }

    return (DigitalInputs[id].Filter.Output == 0u);
}

/*
 * Active-low:
 * Switch turned ON = falling edge = 1 -> 0.
 */
uint8_t AppDigitalInput_TurnedOnEvent(APP_DIGITAL_INPUT_ID id)
{
    if (!AppDigitalInput_IsValidId(id))
    {
        return 0u;
    }

    if (DigitalInputs[id].Edge.FlagFalling)
    {
        DigitalInputs[id].Edge.FlagFalling = 0u;
        return 1u;
    }

    return 0u;
}

/*
 * Active-low:
 * Switch turned OFF = rising edge = 0 -> 1.
 */
uint8_t AppDigitalInput_TurnedOffEvent(APP_DIGITAL_INPUT_ID id)
{
    if (!AppDigitalInput_IsValidId(id))
    {
        return 0u;
    }

    if (DigitalInputs[id].Edge.FlagRising)
    {
        DigitalInputs[id].Edge.FlagRising = 0u;
        return 1u;
    }

    return 0u;
}

uint8_t AppDigitalInput_GetRaw(APP_DIGITAL_INPUT_ID id)
{
    if (!AppDigitalInput_IsValidId(id))
    {
        return 0u;
    }

    return DigitalInputs[id].Filter.Input;
}

uint8_t AppDigitalInput_GetFiltered(APP_DIGITAL_INPUT_ID id)
{
    if (!AppDigitalInput_IsValidId(id))
    {
        return 0u;
    }

    return DigitalInputs[id].Filter.Output;
}

void AppDigitalInput_SetDebounce(APP_DIGITAL_INPUT_ID id, uint16_t debounce_ms)
{
    if (!AppDigitalInput_IsValidId(id))
    {
        return;
    }

    DigitalInputs[id].Filter.VTmax = debounce_ms;
    DigitalInputs[id].Filter.VTcount1 = 0u;
    DigitalInputs[id].Filter.VTcount0 = 0u;
}